"use client";

import Link from "next/link";
import { ExternalLink, MessageSquare } from "lucide-react";
import { useTransition } from "react";
import { updateItemStatus, updateTargetDate } from "@/app/actions";
import { ManagedItem } from "@/lib/data";
import { formatDate, isDueSoon, isOverdue, labelTextColor, statusLabels, type InternalStatus } from "@/lib/utils";

export function ItemTable({ items, kind }: { items: ManagedItem[]; kind: "issue" | "pull_request" }) {
  const [pending, startTransition] = useTransition();
  if (!items.length) return <div className="rounded-xl border border-dashed border-slate-300 py-20 text-center dark:border-zinc-700"><p className="font-medium">No {kind === "issue" ? "issues" : "pull requests"} found</p><p className="mt-1 text-sm text-slate-500">Sync with GitHub or adjust your filters to see your work.</p></div>;
  return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-zinc-800 dark:bg-zinc-950"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500 dark:border-zinc-800"><tr><th className="px-5 py-3 font-medium">Item</th><th className="px-4 py-3 font-medium">Repository</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Target</th><th className="px-4 py-3 font-medium">Activity</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-zinc-900">{items.map((item) => {
    const overdue = isOverdue(item.targetDate, item.status); const dueSoon = isDueSoon(item.targetDate, item.status);
    return <tr key={item.id} className="hover:bg-slate-50/80 dark:hover:bg-zinc-900/50"><td className="max-w-sm px-5 py-4"><Link href={`/items/${item.id}`} className="font-medium hover:text-indigo-600"><span className="mr-2 text-slate-400">#{item.number}</span>{item.title}</Link><div className="mt-1.5 flex flex-wrap gap-1">{item.isDraft && <span className="badge bg-slate-100 text-slate-600 dark:bg-zinc-800 dark:text-zinc-300">Draft</span>}{item.labels.slice(0, 3).map((label) => <span key={label.name} className="badge" style={{ backgroundColor: `#${label.color ?? "cbd5e1"}`, color: labelTextColor(label.color) }}>{label.name}</span>)}</div></td><td className="px-4 py-4 text-slate-600 dark:text-zinc-400">{item.repositoryName}</td><td className="px-4 py-4"><select aria-label={`Status for ${item.title}`} defaultValue={item.status} disabled={pending} onChange={(event) => startTransition(() => updateItemStatus(item.id, event.target.value as InternalStatus))} className="rounded-md border border-slate-200 bg-white px-2 py-1 text-xs font-medium dark:border-zinc-700 dark:bg-zinc-900">{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td className={`px-4 py-4 ${overdue ? "font-medium text-rose-600" : dueSoon ? "font-medium text-amber-600" : "text-slate-500"}`}><input aria-label={`Target date for ${item.title}`} type="date" defaultValue={item.targetDate?.toISOString().slice(0, 10) ?? ""} onChange={(event) => startTransition(() => updateTargetDate(item.id, event.target.value || null))} className="w-30 bg-transparent text-xs outline-none" /><div className="mt-1 text-xs">{overdue ? "Overdue" : dueSoon ? "Due soon" : formatDate(item.targetDate)}</div></td><td className="px-4 py-4 text-slate-500"><span className="inline-flex items-center gap-1"><MessageSquare size={14} />{item.commentCount}</span></td><td className="px-4 py-4"><a href={item.url} target="_blank" rel="noreferrer" aria-label={`Open ${item.title} on GitHub`} className="inline-flex items-center gap-1 rounded-md px-2 py-1.5 text-xs font-medium hover:bg-slate-100 dark:hover:bg-zinc-900">Open <ExternalLink size={13} /></a></td></tr>;
  })}</tbody></table></div>;
}
